### ISSUE TITLE
Trying to register with an existing username does not give an appropriate error.

### ISSUE THREAD

**Issue by runt1m33rr0r** [Team-Genji/League-Of-Ninjas#3]
When I try to register with a taken name, the error shown is a very ugly one. Example:
{"code":11000,"index":0,"errmsg":"insertDocument :: caused by :: 11000 E11000 duplicate key error index: LeagueOfNinjas.users.$username_1  dup key: { : \"test\" }","op":{"updatedAt":"2016-11-27T23:55:00.977Z","createdAt":"2016-11-27T23:55:00.977Z","username":"test","password":"123456","_id":"583b72547e9c3014d276f2d7","__v":0}}

I will give a beer to the person who fixes this nonsense.

**Comment by hmk3r** [comment]
Make them two
Fixed with commit [65baf4e](https://github.com/Team-Genji/League-Of-Ninjas/commit/65baf4eecef4e39a97727057d6db44343d81cd11)
