### ISSUE TITLE
User login does not persist in the forum

### ISSUE THREAD

**Issue by runt1m33rr0r** [Team-Genji/League-Of-Ninjas#9]
When you login in and open the forum, there is no visualisation of being logged in, although you actually are.

**Comment by hmk3r** [comment]
You forgot to pass `user: req.user` to the data object that the `res.render` function uses, therefore pug sees the user as `undefined`
Fixed with commit [0dca1ee](https://github.com/Team-Genji/League-Of-Ninjas/commit/0dca1eeab4238264aa0f39e654043e5310d062b6)
